In [3]:
import numpy as np

A = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [6]:
B = A[0:2, 1:3]
print(A, B)

[[1 2 3]
 [4 5 6]
 [7 8 9]] [[2 3]
 [5 6]]


In [7]:
A[:,2]

array([3, 6, 9])

In [2]:
M = [[-1 for i in range(2)] for j in range(5)]
print(M)

[[-1, -1], [-1, -1], [-1, -1], [-1, -1], [-1, -1]]


In [25]:
class Parent:
    def __init__(self, x1):
        self.x = x1
    def double_x(self):
        self.x *= 2

class Child(Parent):
    def __init__(self, x1, y1):
        Parent.__init__(self, x1)
        self.y = y1
    def double_y(self):
        self.y *= 2

c = Child(2, 2)
c.double_x()
print(c.x, c.y) #Output: 4 2

4 2
